# Exported from Render on 2025-05-31T11:13:01Z
services:
- type: web
  name: Multi-Agent-AI-System
  runtime: python
  repo: https://github.com/msn123-satya/Multi-Agent-AI-System
  plan: free
  envVars:
  - key: GEMINI_API_KEY
    sync: false
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
  autoDeployTrigger: commit
version: "1"
